### ISSUE TITLE
M5.2 full read procedure

### ISSUE THREAD

**Issue by JL01152** [ba114/M5.2#2]
I'm also experimenting with 5.2 DMEs from a 740i. I've got one that I can get a partial read with galleto but for some reason I cant write to it. Besides that the program part of the dme is corrupt or empty and it wont flash with winkfp. How were you able to get a full read of this cc460 chip?
![IMG_20220514_185200](https://user-images.githubusercontent.com/1390301/168951241-82a5051c-1e53-4cb7-8ce2-11e9c23fff0f.jpg)
![IMG_20220514_185243](https://user-images.githubusercontent.com/1390301/168951265-438f18d2-d239-415a-90f5-65543426d4d0.jpg)

**Comment by duduspl** [comment]
I use  quickflash M5.2 m5.2.1
this quickflash on M5.2  was made recently
from this site  https://bmwtuningtools.gumroad.com/l/m52quickflash
[image: image.png]

śr., 18 maj 2022 o 05:39 Jorge Luis ***@***.***> napisał(a):

**Comment by JL01152** [comment]
Nice. I guess I'll give that a try. Do you know if the dme program is stored on the cc460 or on the intel chip? I'm wondering if this will be able to recover that DME?

 I know something happened with the galleto program that when attempting to flash a 16kb file to it, it only changed parts of the original and didn't actually flash the attempted file. May have something to do with the corrupt program in the DME. I did not try to flash the other DME as it is now the only one I have for the car.

**Comment by duduspl** [comment]
I don't know if the dme program is stored on the cc460 or on the intel chip.
Use a k-line adapter to usb and Quickflash program. it works

On full flash  I clone map with pops&bangs  to second ecu
On partial I change rev limiter on romraider and it works !

It's too bad there are so few things in ecu definitions to m5.2 I would
like to change
I'd like to modify pops&bangs




czw., 19 maj 2022 o 14:51 Jorge Luis ***@***.***> napisał(a):

**Comment by JL01152** [comment]
There's zarboz on here on git hub that has a ols file for the 5.2 dme. It's for the 474 but it might be similar to the m44 one. It is very extensive. I'm just a beginner in all this so it'll be a steep climb for me.

**Comment by gerkon56** [comment]
Hello! Please send me full and partial stok files for m44 manual gear.
My email soft325@yandex.ru

I wanted to encode through the winkpf manual transmission, but the ECU died and no longer starts the car.

**Comment by EliasKotlyar** [comment]
Hello everyone,

A friend of mine had to repair E36 318i with a M44 Motor. The ECU ( M5.2) was replaced due to flood damage, and the car was not starting. He was able to "marry" the new ECU with the EWS using "Launch Tool". I was very surprised when he told me that the car started running afterwards. Apparantly that Launch Tool can do that kind of stuff. It might be cheaper solution than trying to develop a NO-EWS patch.

Greatings
Elias

**Comment by NielsDouw** [comment]
Hi! I am searching for the M5.2 definition files for quite some time now. And I can't really find anything that is somewhat close. If someone has those files, I am willing to pay a fair price, please email me! ngcdouw@gmail.com

Regards, Niels

**Comment by Rustle333** [comment]
> 

they are on this page....
