### ISSUE TITLE
M5.2 full read procedure

### ISSUE THREAD

**Issue by NielsDouw** [ba114/M5.2#4]
Hi, sorry for me not understanding. I have extracted a .bin file from my Bosch M5.2 DME with Quickflash m5.2. Now i wanted to load that file into TunerPro but the tables are looking messed up. So i figured that i need another definition file. And thought i could use the one that you made here, but this is a .XML and TunerPro only uses .XDF files. So i am a little lost in what i should do. I have tried to convert .XML to .XDF but it didn't give the results i hoped for. And a proper .XDF file is nowere to be found.
I have a E36 318is M44B19 1996 
Bosch DME M5.2 0 261 203 667

edit: I'm trying to change the bin file on its own in winOLS, but i cant find what the locations are for the rev limiter, fuel tables and ignition tables. if someone knows where they are located, or how i could see where they are located would be a great help.

Kind regards,
Niels

**Comment by Alvarikokex** [comment]
Hi.  How can I connect the M44 (0261203667) DME to a test bench to read the ISN? i find the pinout connection here.   I have the K+DCAN USB interface and an adapter for a 20-pin round connector. Or do I need an ADS protocol interface? thanks.

**Comment by NielsDouw** [comment]
Can you explain what the ISN is and what you could do with it? I cant get a grasp on what it is.

**Comment by Alvarikokex** [comment]
The ISN it is a number inside of memory of the DME , and should match with the EWS. And also they are one more code that need match is he VIN number

**Comment by NielsDouw** [comment]
thnx, but what is it exactly what you need the ISN for?

**Comment by Qbota3** [comment]
> Hi, sorry for me not understanding. I have extracted a .bin file from my Bosch M5.2 DME with Quickflash m5.2. Now i wanted to load that file into TunerPro but the tables are looking messed up. So i figured that i need another definition file. And thought i could use the one that you made here, but this is a .XML and TunerPro only uses .XDF files. So i am a little lost in what i should do. I have tried to convert .XML to .XDF but it didn't give the results i hoped for. And a proper .XDF file is nowere to be found. I have a E36 318is M44B19 1996 Bosch DME M5.2 0 261 203 667
> 
> edit: I'm trying to change the bin file on its own in winOLS, but i cant find what the locations are for the rev limiter, fuel tables and ignition tables. if someone knows where they are located, or how i could see where they are located would be a great help.
> 
> Kind regards, Niels

this .xml it's for RomRider

**Comment by Rustle333** [comment]
RR only
